language: elixir

elixir:
  - 1.3.4
  - 1.4.2

otp_release:
  - 18.3
  - 19.2

script:
  - yes | mix do deps.get
  - mix run -e CommonDeviceDetector.DownloadTasks.run
  - yes | mix test

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
